Added support of Oracle as persistence EF Provider
elsa-workflows/elsa-core pull request #1275
Opened 2021-07-16 14:29 UTC by akghasemi

I have added new project which adds support oracle as persistence EF provider

2021-07-16 14:34 UTC, sfmskywalker requested changes
Awesome, thank you for doing this. I had only a few minor comments about some of the comments. If you could take care of those then I'll merge it in. Thanks!

2021-07-16 14:34 UTC, sfmskywalker commented on src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/DbContextOptionsBuilderExtensions.cs
> +        /// Configures the context to use SqlServer.
Small copy/paste issue: SqlServer -> Oracle

2021-07-16 14:34 UTC, sfmskywalker commented on src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/Elsa.Persistence.EntityFramework.Oracle.csproj
> +            This package provides Entity Framework Core migrations for the PostgreSql database provider.
Small correction: PostgreSql -> Oracle.

2021-07-16 14:34 UTC, sfmskywalker commented on src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Oracle/OracleElsaContextFactory.cs
> +            var connectionString = args.Any() ? args[0] : "Server=127.0.0.1;Port=5432;Database=elsa;User Id=postgres;Password=password;";
Small correction: postgres -> oracle.

2021-07-19 07:48 UTC, sfmskywalker approved these changes

2021-07-19 07:49 UTC, sfmskywalker commented
Looking good. Once you resolve the merge conflicts we can merge it in.

2021-07-20 10:49 UTC, merged

2021-07-20 11:11 UTC, akghasemi commented
thanks