Upgrade all projects to .NET6.0
elsa-workflows/elsa-core pull request #2616
Opened 2021-12-20 20:09 UTC by yopichy

2021-12-20 20:09 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=2616) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=2616) before we can accept your contribution.<br/><br/>:x: yopichy [sign now](https://cla.dotnetfoundation.org/elsa-workflows/elsa-core?pullRequest=2616)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/elsa-workflows/elsa-core?pullRequest=2616) it.</sub>

2021-12-20 20:22 UTC, yopichy commented
@sfmskywalker CI .NET SDK does not support targeting .NET 6.0

2021-12-21 16:15 UTC, sfmskywalker commented
@yopichy Thank you for this! I'll update the CI settings.

2021-12-21 16:16 UTC, sfmskywalker commented
@yopichy Question about this PR: will .NET 5 project still be able to use the Elsa core libraries, Entity Framework etc?

2021-12-21 17:13 UTC, yopichy commented
@sfmskywalker 
Elsa core works with NET 5, but not with EF.
If i removing EFCore.BulkExtensions then it can run on NET 5, but for now I keep the bulk command feature in this PR.
But if you want compatibility with NET 5 I can make it, but sacrifice the bulk command feature or have to replace EFCore.BulkExtensions

2021-12-21 17:43 UTC, sfmskywalker commented
@yopichy We should definitely keep support for .NET 5 for the time being. We should be able to conditionally target both versions of e.g. EFCore.BulkExtensions, right?

E.g.

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="EFCore.BulkExtensions" Version="6.x" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="EFCore.BulkExtensions" Version="5.x" />
</ItemGroup>

<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.1'">
    <PackageReference Include="EFCore.BulkExtensions" Version="3.x" />
</ItemGroup>
```

2021-12-21 18:11 UTC, yopichy commented
@sfmskywalker ok i'll try it

2021-12-21 19:01 UTC, sfmskywalker commented
@yopichy Thank you 🙏🏻

2021-12-21 19:38 UTC, yopichy commented
> @yopichy Thank you 🙏🏻

Done

2021-12-22 09:45 UTC, sfmskywalker commented on src/activities/Elsa.Activities.Http/Elsa.Activities.Http.csproj
> -    </ItemGroup>
Will the removal of these references not break applications targeting .NET 5 and .NET 3.1?

2021-12-23 11:06 UTC, mohdali requested changes
Some changes are required to maintain 3.1 support

2021-12-23 11:16 UTC, sfmskywalker commented on test/component/Elsa.ComponentTests/Elsa.ComponentTests.csproj
> +        <TargetFrameworks>net5.0;net6.0</TargetFrameworks>
Yes, samples & tests should target latest framework only. Only nuget packages need multi-targeting.

2021-12-23 19:01 UTC, mohdali requested changes
minimal changes to get monolith to start running on 3.1, additional changes still required for other persistence packages

2021-12-24 04:03 UTC, yopichy commented
@mohdali @sfmskywalker i'll updated according to suggestion ASAP

2021-12-24 13:41 UTC, mohdali commented on src/server/Elsa.Server.Api/Elsa.Server.Api.csproj
>      <ItemGroup>
```suggestion
    <ItemGroup>
            <FrameworkReference Include="Microsoft.AspNetCore.App" />
```

2021-12-24 15:46 UTC, mohdali commented
@yopichy thank you very much. I went ahead and pushed some updates to implement some of the changes. hope it helps.

2021-12-25 18:51 UTC, yopichy commented
Thanks for the help @mohdali

2021-12-26 21:21 UTC, sfmskywalker approved these changes

2021-12-26 21:31 UTC, merged

2021-12-27 15:19 UTC, DoomerDGR8 commented
This major change affect the Elsa 2.x only?

2022-01-07 12:23 UTC, sfmskywalker commented
More specifically, it only affects `2.4.1` and up.