Mqtt subtitute library + fix retain topics + fix lose message
elsa-workflows/elsa-core pull request #4039
Opened 2023-05-13 13:24 UTC by mircotamburini

- substitute mqtt library System.Net.Mqtt because stills in beta  0.6.16-beta with a more used MQTTnet Version="4.2.0.706"
this library is industry used
- i connect e disconnect broker, not work for retain topic (every time resend all topics)
- fix sometimes connect and disconnect from broker lose some mqtt message

2023-05-15 09:48 UTC, sfmskywalker requested changes
Thanks for the great work! I think that after a little bit of cleanup we can merge it.

2023-05-16 07:24 UTC, mircotamburini commented on src/activities/Elsa.Activities.Mqtt/Services/BusClientFactory.cs
> +                _receivers.Add(options.GetHashCode(), new ( DateTime.Now, newMessageReceiver ));
Sorry, I deleted because not used (take a look new p.r.)

2023-05-16 07:25 UTC, mircotamburini commented on src/activities/Elsa.Activities.Mqtt/Extensions/ServiceCollectionExtensions.cs
> +//using Elsa.Activities.Mqtt.Testing.Handlers;
Sorry, I deleted in the last p.r.
Not necessary

2023-05-21 19:33 UTC, sfmskywalker approved these changes

2023-05-21 19:33 UTC, merged