Service Bus Activities enhancements - Workflow Inbox and Test
elsa-workflows/elsa-core pull request #4512
Opened 2023-10-09 20:26 UTC by jdevillard

This PR add integration testing for Azure Service Bus Activities. 
This PR also modify the Azure Service Bus activities to use the WorkflowInbox

2023-10-15 11:14 UTC, sfmskywalker approved these changes

2023-10-17 21:58 UTC, jdevillard commented
I don't know why all the GUID in the SLN have change ? maybe a mismatch version of my VS2022?

2023-10-18 20:01 UTC, sfmskywalker commented
Indeed, quite strange that it would do that. But as long as the projects and their references remain in tact, I don't think it's an issue.

2023-10-18 20:22 UTC, sfmskywalker commented on test/integration/Elsa.ServiceBusIntegrationTests/Elsa.ServiceBusIntegrationTests.csproj
> +	  <PackageReference Include="Moq" Version="4.18.4" />
Ah, sorry I overlooked this reference - [we no longer use Moq](https://www.youtube.com/watch?v=A06nNjBKV7I). Instead, NSubstitute seems to be a good alternative. There's also FakeItEasy, but hasn't as much traction it seems (not sure why).

2023-10-18 20:23 UTC, sfmskywalker requested changes
Please replace Moq with another mocking package, such as NSubstitute or FakeItEasy.

2023-10-19 15:34 UTC, jdevillard commented
ok SLN conflict is resolved ! if ok for you for the guid change in Sln , seems to be good and this could be merge.

2023-10-19 18:00 UTC, merged