Fixed setting updated and finished date on workflow instance
elsa-workflows/elsa-core pull request #4943
Opened 2024-02-14 14:01 UTC by raymonddenhaan

2024-02-14 19:54 UTC, sfmskywalker requested changes
Looks great, just a small change request 👍🏻

2024-02-15 07:52 UTC, raymonddenhaan commented on src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs
> +        UpdatedAt = SystemClock.UtcNow;
SystemClock is an ISystemClock. It is being injected on line 59:

`SystemClock = serviceProvider.GetRequiredService<ISystemClock>();`

2024-02-15 08:38 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs
> +        UpdatedAt = SystemClock.UtcNow;
You're 100% correct, of course 👍🏻

2024-02-15 08:39 UTC, sfmskywalker approved these changes

2024-02-16 10:58 UTC, sfmskywalker approved these changes

2024-02-16 10:58 UTC, merged