Enhancement/5373 publish
elsa-workflows/elsa-core pull request #5468
Opened 2024-05-30 12:12 UTC by raymonddenhaan

Refactored handling/updating of the ActivityRegistry
- Complete refresh of the registry is done by building a new dictionary, then swapping it. Instead of clearing the working version.
- Creation/Publishing/Retracting/Deleting of a workflow only leads to a change to that specific workflow in the registry instead of recreating the registry from scratch
- Added a failover that on a mis in the registry the entire registry is going to be refreshed.

2024-06-03 06:06 UTC, raymonddenhaan commented
closes #5464

2024-06-04 18:54 UTC, sfmskywalker requested changes

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Dsl/Contracts/IFunctionActivityRegistry.cs
> +    Task<IActivity> ResolveFunction(string functionName, IEnumerable<object?>? arguments = default);
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Dsl/Interpreters/WorkflowDefinitionBuilderInterpreter/VisitObject.cs
> +    private async Task<object> GetObject(ElsaParser.ObjectContext context)
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.JavaScript/Services/JintJavaScriptEvaluator.cs
> +    private static async Task CreateActivityOutputAccessors(Engine engine, ExpressionExecutionContext context)
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs
> +    public async Task<ActivityExecutionContext> CreateActivityExecutionContext(IActivity activity, ActivityInvocationOptions? options = default)
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Contracts/IActivityRegistryLookupService.cs
> +    Task<ActivityDescriptor?> Find(string type);
Please mind the naming convention to apply the `Async` suffix when declaring async methods.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Contracts/IIdentityGraphService.cs
> +    Task AssignIdentities(ActivityNode root);
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Contracts/IWorkflowStateExtractor.cs
> +    Task<WorkflowExecutionContext> Apply(WorkflowExecutionContext workflowExecutionContext, WorkflowState state);
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Services/ActivityRegistryLookupService.cs
> +    private async Task<ActivityDescriptor?> Find(Func<ActivityDescriptor?> findPredicate)
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Services/WorkflowStateExtractor.cs
> +    private static async Task ApplyActivityExecutionContexts(WorkflowState state, WorkflowExecutionContext workflowExecutionContext)
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Services/WorkflowStateExtractor.cs
> +        async Task<ActivityExecutionContext?> CreateActivityExecutionContext(ActivityExecutionContextState activityExecutionContextState)
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Management/Activities/WorkflowDefinitionActivity/WorkflowDefinitionActivity.cs
> +    private async Task CopyInputOutputToVariables(ActivityExecutionContext context)
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Management/Activities/WorkflowDefinitionActivity/WorkflowDefinitionActivity.cs
> +    private async Task<ActivityDescriptor> FindActivityDescriptor(IServiceProvider serviceProvider)
Please mind the naming convention to apply the `Async` suffix when changing methods into async.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Management/Contracts/IActivityRegistryPopulator.cs
> +    void RemoveDefinitionVersionFromRegistry(Type providerType, string workflowDefinitionVersionId, CancellationToken cancellationToken = default);
The IActivityRegistry shouldn't be aware of workflow definitions; it should only be aware of activity descriptor providers.

I missed this the first time the first version of `AddToRegistry(..., workflowdefinitionId)` was added on April 10th, which is my bad. I think this is a mistake and should be revisited.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Management/Notifications/WorkflowDefinitionVersionsUpdate.cs
> +public record WorkflowDefinitionVersionsUpdate(string Id, string DefinitionId, bool UsableAsActivity);
Given that this type represents an update to a single workflow definition version, the name should changed to `WorkflowDefinitionVersionUpdate`.

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Management/Notifications/WorkflowDefinitionVersionsUpdated.cs
> +public record WorkflowDefinitionVersionsUpdated(IEnumerable<WorkflowDefinitionVersionsUpdate> VersionUpdate) : INotification;
`VersionUpdate` should be renamed to `VersionUpdates` (plural).

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Management/Notifications/WorkflowDefinitionVersionsUpdating.cs
> +public record WorkflowDefinitionVersionsUpdating(IEnumerable<WorkflowDefinitionVersionsUpdate> VersionUpdate) : INotification;
`VersionUpdate` should be renamed to `VersionUpdates` (plural).

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Management/Contracts/IActivityRegistryPopulator.cs
> +    void RemoveDefinitionVersionFromRegistry(Type providerType, string workflowDefinitionVersionId, CancellationToken cancellationToken = default);
Additionally, the "populater" exists only to populate the registry, so either we need to rename the service to e.g. "updater", or introduce a separate service called e.g. "depopulator" or "trimmer".

2024-06-04 18:54 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Management/Services/WorkflowDefinitionManager.cs
> -        await EnsureLastVersionIsLatestAsync(definitionId, cancellationToken);
Good thinking 👍🏻

2024-06-06 20:14 UTC, sfmskywalker requested changes
In general, looking good. Just a small request that'll make it tight.

2024-06-06 20:14 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Contracts/IActivityRegistryUpdateService.cs
> +    Task AddToRegistry(Type providerType, string workflowDefinitionId, CancellationToken cancellationToken = default);
Given that this service is specifically designed to update the Activity Registry with Activity Descriptors provided by the WorkflowDefinitionActivityProvider, we can remove the providerType parameter and instead hardcode its use (`typeof(WorkflowDefinitionActivityProvider)`) in the implementing class.

On that note, we should probably also rename this service (IActivityRegistryUpdateService) to something like `WorkflowDefinitionActivityRegistryUpdater`, given that it's not a general-purpose activity registry updater, but rather, a service that handles workflow definition changes by surgically updating the activity registry.

2024-06-06 20:14 UTC, sfmskywalker commented on src/modules/Elsa.Workflows.Core/Services/ActivityRegistryUpdateService.cs
> +            registry.Add(providerType, descriptorToAdd);
Keeping my previous comment in mind, this line would become `registry.Add(typeof(WorkflowDefinitionActivityProvider), descriptorToAdd)`.

2024-06-07 12:01 UTC, merged