Update Methods
elsa-workflows/elsa-core pull request #5801
Opened 2024-07-19 12:25 UTC by KhanbalaRashidov

2024-07-20 10:34 UTC, sfmskywalker approved these changes

2024-08-30 10:06 UTC, sfmskywalker requested changes
I noticed that a lot of the code refactoring involve switching to lambda syntax, which I would like to see undone for all but the smallest functions.

2024-08-30 12:22 UTC, KhanbalaRashidov commented
> I noticed that a lot of the code refactoring involve switching to lambda syntax, which I would like to see undone for all but the smallest functions.

yes

2024-12-12 10:43 UTC, sfmskywalker commented
@KhanbalaRashidov I'm about to close this PR as it adds unwanted changes, but let me know if there are any changes that you feel are useful to have.

2024-12-22 07:40 UTC, closed without merging